# Generated by Django 3.2.25 on 2024-12-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lucky',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('AccNo', models.IntegerField(null=True)),
                ('Place', models.CharField(max_length=50)),
            ],
        ),
    ]
