# Generated by Django 3.2.25 on 2024-12-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0002_auto_20241212_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='boss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeofAcc', models.CharField(max_length=50)),
            ],
        ),
    ]
