# Generated by Django 3.2.25 on 2024-12-18 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0003_boss'),
    ]

    operations = [
        migrations.AddField(
            model_name='boss',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cash.lucky'),
        ),
    ]
