# Generated by Django 3.2.25 on 2024-11-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftDrinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Price', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='products',
            new_name='Food_items',
        ),
    ]
