# Generated by Django 3.2.25 on 2024-11-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0002_auto_20241113_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='softdrinks',
            name='Image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
