# Generated by Django 3.2.25 on 2024-11-14 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0003_softdrinks_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SoftDrinks',
            new_name='TEASHOP',
        ),
    ]
