# Generated by Django 3.2.25 on 2024-11-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0005_rename_teashop_soft_drinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bill_no', models.IntegerField(serialize=111)),
                ('Product_name', models.CharField(max_length=40)),
                ('Total', models.IntegerField()),
            ],
        ),
    ]
