# Generated by Django 3.2.25 on 2024-11-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0006_bill_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_items',
            name='Image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='bill_items',
            name='Bill_no',
            field=models.IntegerField(),
        ),
    ]
