# Generated by Django 3.2.25 on 2024-12-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='Age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='Gender',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
